---
name: Authen-Simple-CDBI
version: 0.1
author:
  - 'Christian Hansen C<ch@ngmedia.com>'
abstract: Simple CDBI authentication
license: perl
requires:
  Authen::Simple: 0.3
  Class::DBI: 0.96
provides:
  Authen::Simple::CDBI:
    file: lib/Authen/Simple/CDBI.pm
    version: 0.1
generated_by: Module::Build version 0.2611
